### ISSUE TITLE
关于微调数据遇到的问题

### ISSUE THREAD

**Issue by AITTSMD** [Tonyfy/LCNN_TRAIN#9]
您好，我是在您训练好的模型上微调自己的数据。我先用了AR人脸数据库进行微调，发现效果很好，准确率挺高。但我用自己采集的数据去微调，结果不收敛，效果很差，loss，accuracy来回震荡。这是我的数据。为了简单的测试，我训练集2个人，每个人100张。虽然数据少，但我觉得应该收敛才对。您觉得是哪里的问题，跟采集设备有没有关系呢？还是参数设置的问题？
![16 08 31 2150_1](https://cloud.githubusercontent.com/assets/21363231/18131353/0cc2aa82-6fc5-11e6-96c5-e633d8fcc33f.png)

**Comment by Tonyfy** [comment]
@AITTSMD  网络输入一致否，输出层是否适配了，最后一层的学习率等参数也要改一下

**Comment by Tonyfy** [comment]
@AITTSMD 不小心关了issue。。。

**Comment by AITTSMD** [comment]
你好，目前我的网络已经训练好了。后来我在测试集上测试，准确率也蛮高。但是我从测试集上拿出一张图片进行分类，发现网络的输出标签是错的，而且网络几乎把测试集中的图片都归为1类（比如类别4）。我又从训练集中拿出一张图片喂到网络中进行分类发现它也把图片归到类别4。我就很奇怪，明明我的测试准确率很高，为什么分类的结果是错误的呢？

**Comment by AITTSMD** [comment]
@

**Comment by AITTSMD** [comment]
@Tonyfy 你好，目前我的网络已经训练好了。后来我在测试集上测试，准确率也蛮高。但是我从测试集上拿出一张图片进行分类，发现网络的输出标签是错的，而且网络几乎把测试集中的图片都归为1类（比如类别4）。我又从训练集中拿出一张图片喂到网络中进行分类发现它也把图片归到类别4。我就很奇怪，明明我的测试准确率很高，为什么分类的结果是错误的呢？

**Comment by AITTSMD** [comment]
@Tonyfy 而且这个网络的输入是单通道的，我应该进行什么样的预处理呢？单纯的灰度图也是3通道。打扰您了，谢谢~现在的目标是输入一张人脸，能够输出正确的类别

**Comment by AITTSMD** [comment]
@Tonyfy 比如说，同样的四张照片（分属四个类别），如果把这四张照片当作测试集用caffe test去测试，输出的标签值都是对的，准确率100%。然后如果把这四张照片喂到网络拿去分类（比如用ipython notebook），输出的标签都是同一个人，都是错的。请问您知道问题在哪里吗？

**Comment by Tonyfy** [comment]
@AITTSMD 
1，模型训练好了，且在自建数据集上准确率高（人脸验证？），说明模型没问题。
2，本网络以解决分类问题来转化求解验证问题，其分类准确率上并不高（10000类，65%）。
3，输出标签都是 同一个人是怎么知道的，你拿到输出层的概率了？都是1？

流程上，调试一下吧。

**Comment by AITTSMD** [comment]
@Tonyfy 
您好，又来打扰您。
1 我自己建立了一个数据集：训练集102个人，每人20张，验证集每人5张，测试集只用了2个人的照片共160张，每人80张。训练模型，最终的验证准确率是99.08%。我在我的测试集上测试模型，不同的两个人照片基本都能识别正确。（人脸分类不是人脸验证）
2 因为我想做成您在博客中手把手教你开发基于深度学习的人脸识别写的那样，可以在视频中检测出人脸并分类而不是要准确率。我就在测试集中拿出照片喂到网络里进行分类，发现输出的标签值是错误的，我又多尝试了几张图片，发现输出的标签值都是错的，而且大多都归到同一类中去（比如第四类）。我输出了概率值发现只有第四类的概率值为1，其他都为0。
3 我非常不理解的是既然用caffe test进行测试准确率很高，单独拿测试集中的图片去分类输出的标签值会是错误的呢？
4 流程上，应该怎么测试呢？
不好意思，打扰您了~

**Comment by Tonyfy** [comment]
@AITTSMD 了解了，用这个网络来做分类，意味着你的测试样本（人物集合A）要是训练样本（人物集合B）的子集，那么输出概率较大的可以认为是判断的类别，在此情景下，“第四类概率为1，其他为0”可以认为是代码有bug（对测试部分代码，调试一下吧，估计是你没有把灰度值除255）。但很不幸，即使修正了代码，这样做也是很不合适的，也不易拓展，因为你不能认不在训练集合中的人。

建议你只是用该模型提取任何人的人脸特征，针对特征完成识别的功能设计，这样就可以拓展到各种应用场景了。

**Comment by AITTSMD** [comment]
@Tonyfy 真的很抱歉，回复您回复的晚了。
1 嗯，对，明白您的意思~训练样本应该是测试样本的子集。测试部分的代码灰度值为什么要除以255呢？我是按照caffe里面分类的那个例子做的。
2 对，不在训练集合中人是认不出来的，不易扩展。您的意思是，我从这个模型中提取到特征，再喂到分类器中（如svm）进行识别吗？
谢谢您的建议~

**Comment by Tonyfy** [comment]
@AITTSMD 
1，我训练时数据除以255了，当然也是猜想，具体你要调试。
2，是的。

**Comment by AITTSMD** [comment]
@Tonyfy 好的，谢谢~除以255后，可以分类成功了，这是为什么呀？下一步就要提取特征了，真是谢谢您。后面有问题还是要麻烦您的，希望自己能做出这个东西出来~

**Comment by AITTSMD** [comment]
@Tonyfy 您好，我又来问问题了。我下面就是提特征了（提取的是eltwise_fc1层的特征）。有几点我不是很清楚:
1 训练集中存在的人 我该怎么提特征呢，是把训练集中的图片喂进网络里，保存eltwise_fc1层后的输出吗？
2 我试了一下，训练集中同一个人的不同图片提取到的特征向量是不一样的，对于这些不同的特征向量，我该进行怎样的操作呢？如何保证这些特征向量类间差异大，类内差异小呢？您当时是怎么做的呢？
3 后面识别的话，应该是衡量特征向量的相似性吧？您是如何衡量的呢？
谢谢~

**Comment by Tonyfy** [comment]
@AITTSMD nice.此时该看看论文了：
1，最后一个隐层是特征描述，
2，CNN模型保证2中的诉求。
3，后面的度量 按照论文中的余弦距离来就很简单了。

**Comment by AITTSMD** [comment]
@Tonyfy 谢谢您的解答，我今天尝试做了一下。我发现呢，在我的测试集的那些图片呢，同一类之间的相似性有些会很低（0.4,0.3甚至还有负的）（可能是不同光照下，不同姿态造成的？），不同类之间的相似性有的很高（0.6）之类的。我想请问您:
1 最后的识别是不是就转换为特征向量的相似性度量？
2 在您的博客手把手教你开发基于深度学习的人脸识别【考勤/签到】系统中，mysql数据库中针对每个人
您保留了几个特征向量呢（单个特征向量我感觉不能满足对不同场景下的需求）？您的阈值是如何考虑的呢？
谢谢~

**Comment by Tonyfy** [comment]
有的会低一些，这里识别可以考虑KNN等方式，度量方法复杂性结合场景来设计就行。

**Comment by AITTSMD** [comment]
@Tonyfy 那您当时数据库中每个人保存了几个特征向量呢？

**Comment by Tonyfy** [comment]
做demo时，凡点了注册的都保存了

**Comment by AITTSMD** [comment]
@Tonyfy 好的，谢谢您的耐心解答

**Comment by AITTSMD** [comment]
@Tonyfy 您好，我想了解一下您是怎么判断某个人是不是属于训练集中的？比如说，来一个陌生人（不是训练集中的人），要输出unknown的标签。我之前想用特征向量的相似性判断，结果发现那个阈值很难判断，因为就同一个人而言，在不同场景下的特征向量相似性也是很低的。那个GAN可以做吗？

**Comment by Tonyfy** [comment]
@AITTSMD 假设是10000个人的候选集合，你拿来一张图片要问他是谁。这个是1：N的搜索问题，要很好的解决此问题，训练模型的数据应该是多少人的呢？100N可能就很好了。当然这个时候，网络模型要变得很复杂了。现在我们的模型是10575个人训练出来的，它所能take 的问题难度是有限的

**Comment by AITTSMD** [comment]
@Tonyfy 真是太谢谢您了~

**Comment by dalehqb** [comment]
@AITTSMD ，你好，请问下分类是怎么解决的，能否分享下分类测试的代码？或者帮忙看看哪里有问题，这个代码是根据demo.py读取写的，但是分类一直不正确。
# -*- coding: UTF-8 -*-
import caffe
import numpy as np
import cv2
def test(my_project_root, deploy_proto):
    caffe_model = my_project_root + 'examples/digits_light_cnn/my.caffemodel'        #caffe_model文件的位置
    img = my_project_root + 'examples/digits_light_cnn/face_1.jpg'                    #随机找的一张待测图片
    labels_filename = my_project_root + 'examples/digits_light_cnn/labels.txt'            #类别名称文件,将数字标签转换回类别名称
    caffe.set_mode_cpu()
    net = caffe.Net(deploy_proto, caffe_model, caffe.TEST)                #加载model和deploy

    #图片预处理设置
    print net.blobs['data'].data.shape
    input = cv2.imread(img,0)
    input = cv2.resize(input,(128,128),interpolation=cv2.INTER_CUBIC)   #we just need to resize the face to (128,128) 
    img_blobinp = input[np.newaxis, np.newaxis, :, :]/255.0    #divide 255.0 ,make input is between 0-1
    net.blobs['data'].reshape(*img_blobinp.shape)
    net.blobs['data'].data[...] = img_blobinp
    net.blobs['data'].data.shape
    out = net.forward()                                                    #执行测试

    labels = np.loadtxt(labels_filename, str, delimiter='\t')           #读取类别名称文件
    prob = net.blobs['fc2'].data[0].flatten()                             #取出最后一层（Softmax）属于某个类别的概率值
    order = prob.argsort()[-1]                                          #将概率值排序，取出最大值所在的序号
    print '图片数字为:',labels[order]                                   #将该序号转换成对应的类别名称，并打印

if __name__ == '__main__':
    my_project_root = "/home/huang/caffe/caffe/"    #my-caffe-project目录
    deploy_proto = my_project_root + "examples/digits_light_cnn/deploy.prototxt"            #保存deploy.prototxt文件的位置
    test(my_project_root, deploy_proto)

**Comment by AITTSMD** [comment]
@dalehqb 单纯这样看很难看出问题啊？你的分类是什么问题呢？是人脸分不对，还是什么？

**Comment by dalehqb** [comment]
嗯，人脸总是分不对，用训练数据也分不对。来自我的华为手机-------- 原始邮件 --------主题：Re: [Tonyfy/LCNN_TRAIN] 关于微调数据遇到的问题 (#9)发件人：陈少萌萌哒 收件人：Tonyfy/LCNN_TRAIN 抄送：dalehqb ,Mention @dalehqb 单纯这样看很难看出问题啊？你的分类是什么问题呢？是人脸分不对，还是什么？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tonyfy/LCNN_TRAIN","title":"Tonyfy/LCNN_TRAIN","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tonyfy/LCNN_TRAIN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AITTSMD in #9: @dalehqb 单纯这样看很难看出问题啊？你的分类是什么问题呢？是人脸分不对，还是什么？"}],"action":{"name":"View Issue","url":"https://github.com/Tonyfy/LCNN_TRAIN/issues/9#issuecomment-319362418"}}}

**Comment by dalehqb** [comment]
能不能把分类的代码发给我参考哈？来自我的华为手机-------- 原始邮件 --------主题：Re: [Tonyfy/LCNN_TRAIN] 关于微调数据遇到的问题 (#9)发件人：陈少萌萌哒 收件人：Tonyfy/LCNN_TRAIN 抄送：dalehqb ,Mention @dalehqb 单纯这样看很难看出问题啊？你的分类是什么问题呢？是人脸分不对，还是什么？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tonyfy/LCNN_TRAIN","title":"Tonyfy/LCNN_TRAIN","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tonyfy/LCNN_TRAIN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AITTSMD in #9: @dalehqb 单纯这样看很难看出问题啊？你的分类是什么问题呢？是人脸分不对，还是什么？"}],"action":{"name":"View Issue","url":"https://github.com/Tonyfy/LCNN_TRAIN/issues/9#issuecomment-319362418"}}}

**Comment by Hanimiao** [comment]
@@@你好，请问如何计算测试图片间的，类内相似性和类间相似性？@AITTSMD

**Comment by qiongxiao** [comment]
> 您好，我是在您训练好的模型上微调自己的数据。我先用了AR人脸数据库进行微调，发现效果很好，准确率挺高。但我用自己采集的数据去微调，结果不收敛，效果很差，loss，accuracy来回震荡。这是我的数据。为了简单的测试，我训练集2个人，每个人100张。虽然数据少，但我觉得应该收敛才对。您觉得是哪里的问题，跟采集设备有没有关系呢？还是参数设置的问题？
> ![16 08 31 2150_1](https://cloud.githubusercontent.com/assets/21363231/18131353/0cc2aa82-6fc5-11e6-96c5-e633d8fcc33f.png)
您好，请问您的这些人脸图像是来自哪个数据集？是可下载的公开人脸数据集吗？
